/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'TriggerAutoApply': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'autoapply.start'; data: never }>
    'SubmitApplicationIfMatch': EventHandler<never, { topic: 'application.submitted'; data: never }>
    'SendEmailNotification': EventHandler<never, never>
    'LoadMockUsers': EventHandler<never, { topic: 'users.loaded'; data: never }>
    'FindNewJobs': EventHandler<never, { topic: 'job.found'; data: never }>
    'DailyAutoApplyTrigger': CronHandler<{ topic: 'autoapply.start'; data: never }>
    'AICompareResumeWithJob': EventHandler<never, { topic: 'match.found'; data: never }>
  }
    
}